services:
  imagemsite:
    image: julianafreires/grupo:imagemsite
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - imagembanco

  imagembanco:
    image: julianafreires/grupo:imagembanco
    ports:
      - "3306:3306"
    networks:
      - rede-compose
      
  imagemr:
    image: julianafreires/grupo:imagemr
    depends_on:
      - imagembanco
    networks:
      - rede-compose

networks:
  rede-compose:
    driver: bridge
