services:
  imagemsite:
    image: julianafreires/site:imagemsite
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - imagembanco

  imagembanco:
    image: julianafreires/site:imagembanco
    ports:
      - "3306:3306"
    networks:
      - rede-compose

  imagemr:
    image: julianafreires/site:imagemr
    networks:
      - rede-compose
    depends_on:
      - imagembanco
    command: ["Rscript", "/app/Dados_tratados.R"]

networks:
  rede-compose:
    driver: bridge
