services:
        site:
                image: julianafreires/site:sitee
                ports:
                       - "8080:8080"
                networks:
                       - rede-compose
                depends_on:
                       - db
        db:
                image: julianafreires/site:imagembanco
                ports: 
                       - "3307:3306"
                networks:
                       - rede-compose
networks:
        rede-compose:
              driver: bridge