services:
  imagemsite:
    image: julianafreires/grupo:imagemsite
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - imagembanco

  imagembanco:
    image: julianafreires/grupo:imagembanco
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: SafeSever
      MYSQL_USER: root
      MYSQL_PASSWORD: urubu100
    ports:
      - "3306:3306"
    networks:
      - rede-compose
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-purubu100"]
      interval: 10s
      timeout: 5s
      retries: 3

  imagemr:
    image: julianafreires/grupo:imagemr
    networks:
      - rede-compose
    depends_on:
      - imagembanco
    environment:
      DB_HOST: imagembanco
      DB_NAME: SafeSever
      DB_USER: root
      DB_PASSWORD: urubu100
    command: ["./wait-for-it.sh", "imagembanco:3306", "--", "Rscript", "/app/Dados_tratados.R"]

networks:
  rede-compose:
    driver: bridge
